
version: 2
root-markers:
  - .git/
loglevel: 0

tools:
  # vim:
  #   lint-command: 'vint -'
  #   lint-stdin: true
  #   lint-formats:
  #     - '%f:%l:%c: %m'

#   markdown:
#     lint-command: 'npx textlint -f unix --stdin'
#     # textlintがmarkdownを考慮しないので
#     # がんばって設定したけど動かなかったが
#     # lint-command: 'npx textlint -f unix --stdin --stdin-filename foo.md | sed -e "s/markdown/text/g"'
#     # lint-stdin:false で解決
#     lint-stdin: false
#     lint-formats:
#         - '%f:%l:%c: %m'


  textlint: &textlint
    lint-command: 'npx textlint --format unix '
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'

  # tex:
  #   lint-command: 'chktex -v0 -q'
  #   lint-stdin: true
  #   lint-formats:
  #       - '%f:%l:%c:%n:%m'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  txt:
    - <<: *textlint

  markdown:
    - <<: *textlint

  yaml:
    - <<: *yaml-yamllint
