[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo =  'roxma/nvim-yarp'
#on_if = '!has('nvim')'

[[plugins]]
repo =  'roxma/vim-hug-neovim-rpc'
#on_if = '!has('nvim')'

[[plugins]]
repo =  'deton/jasegment.vim'
hook_add = '''
let g:jasegment#model='knbc_bunsetu'
let g:jasentence_endpat = '[。．？！]\+'
'''

[[plugins]]
repo =  'kshenoy/vim-signature'

[[plugins]]
repo =  'maximbaz/lightline-ale'
depends = ['lightline']
hook_add = '''
let g:lightline#ale#indicator_checking = "\uf110"
let g:lightline#ale#indicator_warnings = "\uf48f"
let g:lightline#ale#indicator_errors = "\uf484"
let g:lightline#ale#indicator_ok = "\uf43a"
'''

[[plugins]]
repo =  'Shougo/neomru.vim'
hook_add ='''
"denite-neomruでginaを無視
let g:neomru#file_mru_ignore_pattern = 'gina://'
let g:neomru#time_format = '%Y/%m/%d %H:%M:%S'
let g:neomru#file_mru_limit = 100
let g:neomru#file_mru_path= '~/.cache/neomru/file'
'''

[[plugins]]
repo =  'basyura/twibill.vim'

[[plugins]]
repo =  'mattn/webapi-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo =  'mengelbrecht/lightline-bufferline'
depends = ['lightline.vim']

[[plugins]]
repo =  'itchyny/vim-gitbranch'
depends = ['lightline.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo ='ayu-theme/ayu-vim'

[[plugins]]
repo = 'yarisgutierrez/ayu-lightline'
depends = ['lightline.vim']

[[plugins]]
repo =  'morhetz/gruvbox'
hook_add = '''
let g:gruvbox_contrast_dark = 'medium'
let g:gruvbox_italicize_comments = 0
let g:gruvbox_invert_selection = 0
let g:gruvbox_guisp_fallback = 'bg'
'''
[[plugins]]
repo = 'markonm/traces.vim'
hook_add ='''
let g:traces_num_range_preview = 1
nnoremap S :%s/
'''

[[plugins]]
repo = 'vim-pandoc/vim-pandoc'
hook_add = '''
let g:pandoc#modules#disabled = ["formatting","chdir", "spell"]
let g:pandoc#folding#fdc = 0
let g:pandoc#filetypes#handled = ["pandoc", "markdown"]
let g:pandoc#filetypes#pandoc_markdown=0
'''

[[plugins]]
repo = 'Shougo/neco-syntax'
hook_add = '''
let g:neocomplete#sources#syntax#min_keyword_length = 3
'''

[[plugins]]
repo = 'vim-pandoc/vim-pandoc-syntax'
hook_add = '''
let g:pandoc#syntax#conceal#use = 0
'''
[[plugins]]
repo = 'hrsh7th/vim-neco-calc'
on_source = ['deoplete','neocomplete']

# vim:set foldmethod=marker:
