[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo =  'roxma/nvim-yarp'
if = '''! has('nvim')'''

[[plugins]]
repo =  'roxma/vim-hug-neovim-rpc'
if = '''! has('nvim')'''

[[plugins]]
repo =  'deton/jasegment.vim'
hook_source = '''
let g:jasegment#model='knbc_bunsetu'
let g:jasentence_endpat = '[。．？！]\+'
'''

[[plugins]]
repo =  'kshenoy/vim-signature'

[[plugins]]
repo =  'maximbaz/lightline-ale'
depends = ['lightline']
hook_add = '''
let g:lightline#ale#indicator_checking = "\uf110"
let g:lightline#ale#indicator_warnings = "\uf48f"
let g:lightline#ale#indicator_errors = "\uf484"
let g:lightline#ale#indicator_ok = "\uf43a"
'''

[[plugins]]
repo =  'itchyny/vim-gitbranch'
depends = ['lightline']

[[plugins]]
repo =  'Shougo/neomru.vim'
hook_source ='''
"denite-neomruでginaを無視
let g:neomru#file_mru_ignore_pattern = 'gina://'
'''

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo =  'mengelbrecht/lightline-bufferline'

#[[plugins]]
#repo =  'Shougo/echodoc.vim'

[[plugins]]

repo = 'cocopon/iceberg.vim'
#on_if = ''' g:colors_name='iceberg' '''

#[[plugins]]
#repo =  'w0ng/vim-hybrid'
#on_if = ''' g:colors_name='hybrid' '''

#[[plugins]]
#repo =  'morhetz/gruvbox'#}}}
#on_if = ''' g:colors_name='gruvbox' '''
#hook_source = '''
#let g:gruvbox_contrast_dark = 'medium'
#let g:gruvbox_italicize_comments = 0
#let g:gruvbox_invert_selection = 0
#let g:gruvbox_guisp_fallback = 'bg'
#'''

#[[plugins]]
#repo = 'ryanoasis/vim-devicons'
#hook_add = '''
#let g:webdevicons_enable_denite = 1
#let g:webdevicons_enable_unite = 1
#'''
# vim:set foldmethod=marker:
