[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo =  'roxma/nvim-yarp'
if = '''! has('nvim')'''

[[plugins]]
repo =  'roxma/vim-hug-neovim-rpc'
if = '''! has('nvim')'''

[[plugins]]
repo =  'deton/jasegment.vim'
hook_source = '''
let g:jasegment#model='knbc_bunsetu'
let g:jasentence_endpat = '[。．？！]\+'
'''

[[plugins]]
repo =  'kshenoy/vim-signature'

[[plugins]]
repo =  'maximbaz/lightline-ale'
depends = ['lightline']

[[plugins]]
repo =  'itchyny/vim-gitbranch'
depends = ['lightline']

[[plugins]]
repo =  'Shougo/neomru.vim'
hook_source ='''
"denite-neomruでginaを無視
let g:neomru#file_mru_ignore_pattern = 'gina://'
'''

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo =  'mengelbrecht/lightline-bufferline'

#[[plugins]]
#repo =  'Shougo/echodoc.vim'

[[plugins]]
repo =  'kmnk/denite-dirmark'
hook_add = '''
"{{{
nmap [denite]d <Plug>(denite-dirmark)
nmap [denite]D <Plug>(denite-dirmark-add)
"open dirmark-bookmark in Denite
nnoremap <silent> <Plug>(dirmark) 
    \:<C-u>Denite -mode=normal -buffer-name=normal dirmark<CR>
"bookmark by "add"action
nnoremap <silent><expr><nowait> <Plug>(dirmark-add) 
    \:<C-u>DeniteBufferDir dirmark/add <CR>
"open in defx
nmap [denite]x <Plug>(defx):Denite 
    \ -buffer-name=normal -mode=normal
    \ defx/dirmark <CR>
"}}}
'''
[[plugins]]
repo =  'tyru/eskk.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
#on_if = ''' g:colors_name='iceberg' '''

#[[plugins]]
#repo =  'w0ng/vim-hybrid'
#on_if = ''' g:colors_name='hybrid' '''

#[[plugins]]
#repo =  'morhetz/gruvbox'#}}}
#on_if = ''' g:colors_name='gruvbox' '''
#hook_source = '''
#let g:gruvbox_contrast_dark = 'medium'
#let g:gruvbox_italicize_comments = 0
#let g:gruvbox_invert_selection = 0
#let g:gruvbox_guisp_fallback = 'bg'
#'''

#[[plugins]]
#repo = 'ryanoasis/vim-devicons'
#hook_add = '''
#let g:webdevicons_enable_denite = 1
#let g:webdevicons_enable_unite = 1
#'''
# vim:set foldmethod=marker:
