[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo =  'roxma/nvim-yarp'
if = '''! has('nvim')'''

[[plugins]]
repo =  'roxma/vim-hug-neovim-rpc'
if = '''! has('nvim')'''

[[plugins]]
repo =  'deton/jasegment.vim'
hook_add = '''
let g:jasegment#model='knbc_bunsetu'
let g:jasentence_endpat = '[。．？！]\+'
'''

[[plugins]]
repo =  'kshenoy/vim-signature'

[[plugins]]
repo =  'maximbaz/lightline-ale'
depends = ['lightline']
hook_add = '''
let g:lightline#ale#indicator_checking = "\uf110"
let g:lightline#ale#indicator_warnings = "\uf48f"
let g:lightline#ale#indicator_errors = "\uf484"
let g:lightline#ale#indicator_ok = "\uf43a"
'''

[[plugins]]
repo = 'haya14busa/vim-migemo'
hook_add = '''
set migemo
'''

[[plugins]]
repo =  'Shougo/neomru.vim'
hook_add ='''
"denite-neomruでginaを無視
let g:neomru#file_mru_ignore_pattern = 'gina://'
'''

[[plugins]]
repo =  'basyura/twibill.vim'

[[plugins]]
repo =  'mattn/webapi-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo =  'mengelbrecht/lightline-bufferline'
depends = ['lightline.vim']

[[plugins]]
repo =  'itchyny/vim-gitbranch'
depends = ['lightline.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo ='ayu-theme/ayu-vim'

[[plugins]]
repo = 'yarisgutierrez/ayu-lightline'
depends = ['lightline.vim']

[[plugins]]
repo =  'morhetz/gruvbox'
hook_add = '''
let g:gruvbox_contrast_dark = 'medium'
let g:gruvbox_italicize_comments = 0
let g:gruvbox_invert_selection = 0
let g:gruvbox_guisp_fallback = 'bg'
'''

[[plugins]]
repo = 'markonm/traces.vim'
hook_add ='''
let g:traces_num_range_preview = 1
nnoremap S :s//gc<Left><Left><Left>
'''

# vim:set foldmethod=marker:
