[[plugins]]
repo = 'vim-denops/denops.vim'

# [[plugins]]
# lazy = 1
# on_cmd = ['GhostStart']
# repo = 'gamoutatsumi/dps-ghosttext.vim'

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = ['denops.vim']

[[plugins]]
# lazy = 1
on_cmd = ['Gin']
repo = 'lambdalisue/gin.vim'
hook_add = '''
nnoremap <silent> <Leader>gg
\ <Cmd>GinStatus<CR>
nnoremap <silent> <Leader>gb
\ <Cmd>GinBranch --all<CR>
nnoremap <silent> <Leader>gl
\ <Cmd>GinLog ++opener=botright\ vsplit<CR>
nnoremap <silent> <Leader>ga
\ <Cmd>Gin ++wait add %:p<bar>Gin commit<CR>

let g:gin_proxy_editor_opener='split'
"nnoremap <silent> <Leader>gc
"\ <Cmd>GinBuffer ++opener=botright\ split commit<CR>
nnoremap <silent> <Leader>gc <Cmd>Gin commit<CR>
nnoremap <silent> <Leader>gC <Cmd>Gin commit --amend<CR>
nnoremap <silent> <Leader>gd <Cmd>call <SID>compare_commitish(0)<CR>
nnoremap <silent> <Leader>gD <Cmd>call <SID>compare_commitish(1)<CR>
" nnoremap <silent> <Leader>gD <Cmd>call execute('let @* = "'.. input('commitish: ') ..'"\|GinEdit ++opener=tabedit ' .. expand(@*) .. ' %:p \|diffthis\|GinEdit ++opener=vsplit ' .. expand(@*).. '^  %\|diffthis')<CR>

function! s:compare() abort
tabedit %
setlocal scrolloff=999
diffthis
GinEdit! %:p ++opener=vsplit
setlocal scrolloff=999
diffthis
wincmd p
norm! ]c
endfunction

function! s:compare_commitish(flag) abort
if a:flag ==# 0
  call s:compare()
  return
endif
let commitish = input('commitish(default: head): ', "head")
call execute('GinEdit ' .. '++opener=tabedit ' .. expand(commitish) .. ' %:p')
setlocal scrolloff=999
diffthis
let from = input('diff_from(default: head^): ', "head^")
call execute('GinEdit ' .. '++opener=vsplit ' .. expand(from)  .. ' %')
setlocal scrolloff=999
diffthis
wincmd p
norm! ]c
endfunction
let g:gin_log_persistent_args = ['++emojify', '--graph', '--abbrev-commit', '--pretty=format:%Cred%h%Creset %s %d %cr %C(blue)<%an>%Creset']
"'--pretty=format:%Cred%h%Creset %s %C(yellow)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset'
let g:gin_status_persistent_args = ['++opener=botright 15split']
let g:gin_branch_persistent_args = ['++opener=botright 15split']
let g:gin_proxy_apply_without_confirm = 1

au vimrc BufEnter * if &ft =~# 'gin-.*' | call <SID>gin_mapping() | endif
function! s:gin_mapping() abort
  nnoremap <buffer> q <cmd>close<CR>
endfunction

function! s:define_gin_local() abort
  setlocal bufhidden=hide
  setlocal buftype=nofile
  setlocal nobuflisted
  setlocal noswapfile
  command! -buffer -bar GinLocal execute 'edit' gin#util#expand('%')
  nnoremap <buffer> q <cmd>close<CR>
endfunction

augroup my-gin-local
  autocmd BufReadCmd ginedit://* call s:define_gin_local()
  autocmd BufReadCmd gindiff://* call s:define_gin_local()
  autocmd FileType gin call s:define_gin_local()
  " autocmd BufReadCmd ginlog://* call s:define_gin_local()
augroup END
'''

[[plugins]]
repo = 'Shougo/ddc.vim'
# lazy = 1
# depends = ['denops.vim', 'pum.vim']
# on_event = ['InsertEnter', 'CmdlineEnter']
hook_add = "call execute('source ' .. stdpath('config') .. '/rc/config/ddc.rc.vim')"

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'

[[plugins]]
repo = 'Shougo/ddc-cmdline'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'vim-skk/skkeleton'
hook_add = '''
imap <C-j> <Plug>(skkeleton-toggle)
cmap <C-j> <Plug>(skkeleton-enable)
xnoremap <C-j> c<Cmd>call skkeleton#handle('enable', {})<CR><Cmd>call skkeleton#handle('handleKey', {'key': [';', getreg()]})<CR>
autocmd dein ColorScheme * hi InInsertSign gui=bold guifg=#84a0c6
autocmd dein ColorScheme * hi InEskkKanaSign gui=bold guifg=#e2a478
let s:insertpos = 0
let s:insert_icon = '▶'

call sign_define('InInsert',{'text':s:insert_icon,'texthl':'InInsertSign' ,'priority': 50 })
call sign_define('InEskkKana',{'text':s:insert_icon,'texthl':'InEskkKanaSign', 'priority': 50 })
call sign_define('InEskkKat',{'text':s:insert_icon,'texthl':"Constant" ,'priority': 51 })

au vimrc InsertEnter * let s:insertpos = line('.') | call s:insert_highlight()
au vimrc CursorMovedI * if s:insertpos != line('.') | call s:insert_highlight() | let s:insertpos = line('.') | endif

if has('nvim')
au vimrc InsertLeavePre * call sign_unplace('Ins')
else
au vimrc InsertLeave * call sign_unplace('Ins')
endif

function! s:insert_highlight() abort
call sign_unplace('Ins')
if &l:iminsert
call sign_place( 15,'Ins','InEskkKana','%',{'lnum':line('.')} )
else
call sign_place( 10,'Ins','InInsert','%',{'lnum':line('.')} )
endif
endfunction

autocmd vimrc User skkeleton-enable-post call s:highlight_imesign_on()
autocmd vimrc User skkeleton-disable-post call s:highlight_imesign_off()

function! s:highlight_imesign_off()
if mode() is# 'c' | return | endif
lua vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#84a0c6' })
endfunction

function! s:highlight_imesign_on()
if mode() is# 'c' | return | endif
lua vim.api.nvim_set_hl(0, 'InInsertSign', { fg= '#e2a478'})
endfunction
lua << EOF
vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#84a0c6' })
local autocmd = vim.api.nvim_create_autocmd
local augroup = vim.api.nvim_create_augroup
autocmd({ 'ModeChanged' }, {
  group = 'dein',
  callback = function()
    local current_mode = vim.fn.mode()
    if current_mode == 'n' then
      vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#c6c8d1' })
      -- vim.fn.sign_define('smoothcursor', { text = 'V' }) -- you can also change the cursor shape.
    elseif current_mode == 'v' or current_mode == 'V' then
      vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#b4be82' })
    elseif current_mode == 'i' then
      vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#84a0c6' })
    end
  end,
})
autocmd({ 'User' }, {
  pattern = 'skkeleton-mode-changed',
  group = 'dein',
  callback = function()
    local current_mode = vim.api.nvim_eval('g:skkeleton#mode')
    if current_mode == 'hira' then
      vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#84a0c6' })
      -- vim.fn.sign_define('InInsertSign', { text = 'V' }) -- you can also change the cursor shape.
    elseif current_mode == 'kata' then
      vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#DF81A2' })
    elseif current_mode == 'abbrev' then
      vim.api.nvim_set_hl(0, 'InInsertSign', { fg = '#149116' })
    end
  end,
})
EOF

let skk_global_dict = isdirectory(expand('~/GoogleDrive')) ? glob('~/GoogleDrive/config/.skk/SKK-JISYO.*', v:false, v:true) : ['~/.skk/SKK-JISYO.L']
let skk_user_dict = isdirectory(expand('~/GoogleDrive')) ? expand('~/GoogleDrive/config/.skk/.skk-jisyo') : '.skk/.skk-jisyo'
call skkeleton#config({
\ 'globalDictionaries': skk_global_dict,
\ 'userDictionary': skk_user_dict,
\ 'completionRankFile': expand('~/.skk/rank.json'),
\ 'eggLikeNewline': v:true,
\ 'debug': v:false,
\ 'registerConvertResult': v:true,
\ 'showCandidatesCount': 3,
\ 'immediatelyCancel': v:false,
\ 'keepState': v:false,
\})
" call add(g:skkeleton#mapped_keys, '<C-CR>')
" call add(g:skkeleton#mapped_keys, '<C-w>')
" call skkeleton#register_keymap('henkan', '<C-w>', 'cancel')
" call skkeleton#register_keymap('henkan', '<C-CR>', 'kakutei')
call skkeleton#register_kanatable('rom', {
\ "z\<Space>": ["\u3000", ''],
\ 'va': ['ゔぁ', ''],
\ 'vi': ['ゔぃ', ''],
\ 'vu': ['ゔ', ''],
\ 've': ['ゔぇ', ''],
\ 'vo': ['ゔぉ', ''],
\ 'ca': ['か', ''],
\ 'ci': ['し', ''],
\ 'cu': ['く', ''],
\ 'ce': ['せ', ''],
\ 'co': ['こ', ''],
\ 'xn': ['ん', ''],
\ 'zn': ['〓', ''],
\ 'zb': ['■', ''],
\ 'zm': ['●', ''],
\ 'zss': ['▼', ''],
\ 'zsu': ['▲', ''],
\ 'zsa': ['☆', ''],
\ 'zv': ['★', ''],
\ 'zx': ['○', ''],
\ 'zds': ['◇', ''],
\ 'zdk': ['◆', ''],
\ 'z1': ['１', ''],
\ 'z2': ['２', ''],
\ 'z3': ['３', ''],
\ 'z4': ['４', ''],
\ 'z5': ['５', ''],
\ 'z6': ['６', ''],
\ 'z7': ['７', ''],
\ 'z8': ['８', ''],
\ 'z9': ['９', ''],
\ 'z0': ['０', ''],
\ 'zz0': ['⓪ ', ''],
\ 'zz1': ['①', ''],
\ 'zz2': ['②', ''],
\ 'zz3': ['③', ''],
\ 'zz4': ['④', ''],
\ 'zz5': ['⑤', ''],
\ 'zz6': ['⑥', ''],
\ 'zz7': ['⑦', ''],
\ 'zz8': ['⑧', ''],
\ 'zz9': ['⑨', ''],
\ 'z-': ['-', ''],
\ '(': ['（', ''],
\ ')': ['）', ''],
\ 'z(': ['(', ''],
\ 'z)': [')', ''],
\ 'z{': ['【', ''],
\ 'z}': ['】', ''],
\ '{': ['［', ''],
\ '}': ['］', ''],
\ 'z%': ['％', ''],
\ 'z.': ['…', ''],
\ '~': ['〜', ''],
\ 'z/': ['・', ''],
\ 'z,': ['●', ''],
\ })

call skkeleton#register_keymap('input', ';', 'henkanPoint')
'''
# [[plugins]]
# repo ='kat0h/bufpreview.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
depends = ['pum.vim']
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_length'

[[plugins]]
repo = 'matsui54/ddc-converter_truncate'

# [[plugins]]
# repo = 'matsui54/denops-signature_help'
# #on_source = ['ddc.vim']
# depends = ['denops.vim']
# hook_source = '''
# call signature_help#enable()
# '''

[[plugins]]
repo = 'Shougo/ddu.vim'
# [[plugins]]
# repo = 'Milly/ddu.vim'
# rev = 'source-stream'
# merged = 0
hook_add = '''
call execute('source ' .. stdpath('config') .. '/rc/config/ddu_mapping.rc.vim')
call execute('source ' .. stdpath('config') .. '/rc/config/ddu.rc.vim')
'''
hook_source = '''
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
[[plugins]]
# lazy = 1
# on_source = ['ddu.vim']
# merged = 0
repo = 'Shougo/ddu-ui-ff'
[[plugins]]
repo = 'Shougo/ddu-source-file'
[[plugins]]
repo = 'Shougo/ddu-kind-file'
[[plugins]]
repo = 'Shougo/ddu-source-file_point'
[[plugins]]
repo = 'Shougo/ddu-source-file_old'
[[plugins]]
repo = 'Shougo/ddu-source-line'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
[[plugins]]
repo = 'Shougo/ddu-kind-word'
[[plugins]]
repo ='shun/ddu-source-buffer'
[[plugins]]
repo ='kuuote/ddu-source-mr'
[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
[[plugins]]
repo = 'matsui54/ddu-source-file_external'
[[plugins]]
repo = 'matsui54/ddu-source-help'
# [[plugins]]
# repo = 'gamoutatsumi/ddu-source-nvim-lsp'
[[plugins]]
repo = 'shun/ddu-source-rg'
[[plugins]]
repo = 'Shougo/ddu-source-action'
[[plugins]]
repo = 'kuuote/ddu-matcher-fuse'
[[plugins]]
repo = 'matsui54/ddu-filter-fzy'
[[plugins]]
repo = 'Bakudankun/ddu-source-dirmark'
[[plugins]]
repo = 'nekowasabi/ddu-filter-matcher_migemo'
[[plugins]]
repo = 'matsui54/ddc-postfilter_score'
[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
# [[plugins]]
# # lazy = 1
# on_cmd = ['Glance']
# repo = 'tani/glance-vim'
# hook_source = '''
# " let g:glance#plugins = ['https://esm.sh/markdown-it-checkbox']
# '''
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
[[plugins]]
# lazy = 1
# on_source = ['ddu.vim']
repo = 'Shougo/ddu-ui-filer'
[[plugins]]
repo = 'Bakudankun/ddu-filter-matchfuzzy'
# [[plugins]]
# repo = 'matsui54/ddu-vim-ui-select'
[[plugins]]
repo = 'Shougo/ddu-column-filename'
[[plugins]]
repo = 'Shougo/ddu-source-vim'
[[plugins]]
repo = 'k-ota106/ddu-source-marks'
[[plugins]]
repo = 'matsui54/denops-signature_help'
[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'

[[plugins]]
repo = 'mikanIchinose/ddu-source-markdown'

[[plugins]]
repo = 'Milly/ddc-source-register'

[[plugins]]
repo = 'yukimemi/dps-hitori'
hook_add = '''
let g:hitori_debug = v:false  " debug console.log
let g:hitori_quit = v:false    " whether to exit after attaching
let g:hitori_ignore_patterns = ["\\.tmp$", "\\.diff$", "\\.eml$", "(COMMIT_EDIT|TAG_EDIT|MERGE_|SQUASH_)MSG$"]
'''

[[plugins]]
repo = 'Milly/ddu-filter-kensaku'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'

[[plugins]]
repo = 'lambdalisue/kensaku-command.vim'

[[plugins]]
repo = 'lambdalisue/kensaku-search.vim'
on_event = ['BufEnter']
lazy = 1
merged = 0
hook_source = '''
cnoremap <CR> <Plug>(kensaku-search-replace)<CR>
'''

# [[plugins]]
# if = 'executable("gh")'
# repo = 'skanehira/denops-gh.vim'

[[plugins]]
repo = 'Milly/ddu-filter-merge'

# [[plugins]]
# repo = 'hasundue/ddu-filter-zf'
# build = 'deno task build'

[[plugins]]
repo = 'Shougo/ddc-ui-inline'

# [[plugins]]
# repo = 'tennashi/ddu-source-git'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'

[[plugins]]
repo ='kuuote/ddu-source-git_diff'

[[plugins]]
repo = 'Shougo/ddu-source-dummy'

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'

[[plugins]]
repo = 'uga-rosa/ddc-source-lsp-setup'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'https://github.com/lambdalisue/http-protocol.vim'

[[plugins]]
repo = 'kyoh86/ddu-source-github'

[[plugins]]
repo = 'Shougo/ddu-source-path_history'

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'

# [[plugins]]
# repo = 'Milly/windows-clipboard-history.vim'

[[plugins]]
repo = 'kamecha/ddu-source-tab'

[[plugins]]
repo = 'tani/hey.vim'
