# [[plugins]]
# repo = 'Shougo/ddc.vim'
# hook_add = '''
# " Customize global settings
# " Use around source.
# call ddc#custom#patch_global('sources', ['around'])
# " Enable default matcher.
# call ddc#custom#patch_global('sourceOptions', {
#       \ '_': {'matchers': ['matcher_head']},
#       \ })
# " Change source options
# call ddc#custom#patch_global('sourceOptions', {
#       \ 'around': {'matchers': ['matcher_head'], 'mark': 'A'},
#       \ })
# call ddc#custom#patch_global('sourceParams', {
#       \ 'around': {'maxSize': 500},
#       \ })

# " Customize settings on a filetype
# call ddc#custom#patch_filetype(['c', 'cpp'], 'sources', ['around', 'clangd'])
# call ddc#custom#patch_filetype(['c', 'cpp'], 'sourceOptions', {
#       \ 'clangd': {'mark': 'C'},
#       \ })
# call ddc#custom#patch_filetype('markdown', 'sourceParams', {
#       \ 'around': {'maxSize': 100},
#       \ })

# " Use ddc.
# call ddc#enable()
# '''
# [[plugins]]
# repo = 'vim-denops/denops.vim'
# hook_add = '''
# let g:denops#deno = 'C:\ProgramData\chocolatey\bin\deno.exe'
# '''

[[plugins]]
repo =  'Shougo/deoplete.nvim'
# on_if = 'has("nvim")'
on_event = 'InsertEnter'
hook_source = 'source ~/dotfiles/nvim/rc/config/deoplete.rc.vim'

# [[plugins]]
# rev = 'dev'
# repo = 'hrsh7th/nvim-cmp'
