[[plugins]]
repo = 'Shougo/ddc.vim'
hook_source = '''
'''

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

# [[plugins]]
# repo =  'Shougo/deoplete.nvim'
# # on_if = 'has("nvim")'
# on_event = 'InsertEnter'
# hook_source = 'source ~/dotfiles/nvim/rc/config/deoplete.rc.vim'

# [[plugins]]
# rev = 'dev'
# repo = 'hrsh7th/nvim-cmp'
