[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
"let g:denops#debug = 1
'''

[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'

[[plugins]]
repo = 'Shougo/ddc.vim'
# lazy = 1
# on_event = 'InsertEnter'
hook_add = '''
" Customize global settings

" Use around source.
" https://github.com/Shougo/ddc-around
" Use matcher_head and sorter_rank.
" https://github.com/Shougo/ddc-matcher_head
" https://github.com/Shougo/ddc-sorter_rank

" Change source options
call ddc#custom#patch_global({
\ 'completionMode': 'popupmenu',
\ 'smartCase': v:true,
\ })
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'matchers': ['matcher_fuzzy'],
      \   'sorters': ['sorter_rank'],
      \ },
      \ 'around': {'mark': 'A'},
      \ 'necovim': {'mark': 'V'},
      \ 'eskk': {'mark': '▼', 'matchers': [], 'sorters': []},
      \ })

call ddc#custom#patch_global('sourceParams', {
      \ 'around': {'maxSize': 500},
      \ })

" Customize settings on a filetype
call ddc#custom#patch_filetype(
    \ ['vim', 'toml'], 'sources', ['necovim', 'around']
    \ )
call ddc#custom#patch_filetype('markdown', 'sourceParams', {
      \ 'around': {'maxSize': 100},
      \ })
call ddc#custom#patch_global('sources', ['eskk','around'])

call ddc#custom#patch_global('sources', ['nvimlsp'])
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {'matchers': ['matcher_fuzzy']},
      \ 'nvimlsp': {'mark': 'lsp', 'forceCompletionPattern': '\.|:|->'},
      \ })

" Use ddc.
call ddc#enable()
'''

