# ~/.goneovim/setting.toml

[Editor]
# Editor minimum window width (>= 800)
Width = 1000
# Editor minimum window height (>= 600)
Height = 1200

StartMaximizedWindow = false

# Editor external font-family, font-size, and linespace.
FontFamily = "RictyDiminished NF"
FontSize = 12
Linespace = 1

# Copy yanked text to clipboard
Clipboard = true

# Disable IME in Normal mode
DisableImeInNormal = true

# Drawing window and Transparent breaks statusline and tabline.
## Transparent window alpha
## Note: This setting also implicitly enables the Drawborder setting
#Transparent = 0.95
##
## Drawing window border instead of vertical split, statusline
#DrawBorder = true

ExtCmdline = false
ExtPopupmenu = false
ExtTabline = false
ExtMessages = false

IndentGuide = true

[Statusline]
Visible = false

# Options: “textLabel” / “icon” / “background” / “none”
ModeIndicatorType = "background"

# Optional setting colors per Neovim editing modes
NormalModeColor = "#3cabeb"
CommandModeColor = "#5285b8"
InsertModeColor = "#2abcb4"
ReplaceModeColor = "#ff8c0a"
VisualModeColor = "#9932cc"
TerminalModeColor = "#778899"

# Statusline components
Left = [ "mode", "filepath", "filename" ]
Right = [ "message", "git", "filetype", "fileformat", "fileencoding", "curpos", "lint" ]

[Palette]
Transparent = 0.8

[Message]
Transparent = 0.8

[Popupmenu]
# show detail column
ShowDetail = true
# total number to display item
Total = 20
# width of `menu` column
MenuWidth = 400
# width of `info` column
InfoWidth = 1
# width of `detail` column
DetailWidth = 250


[Tabline]
Visible = true

[Lint]
Visible = false

[ScrollBar]
Visible = false

[MiniMap]
Visible = false
# # Restore session — information that was ended without being saved
# RestoreSession = false

# File open command in gonvim file explorer
