# ~/.goneovim/setting.toml

[Editor]
# Editor minimum window width (>= 800)
Width = 1000
# Editor minimum window height (>= 600)
Height = 850

StartMaximizedWindow = false

# Editor external font-family, font-size, and linespace.
FontFamily = "RictyDiminished NF"
FontSize = 12
Linespace = 1

# Copy yanked text to clipboard
Clipboard = false

# Disable IME in Normal mode
DisableImeInNormal = true

DrawShadowForFloatWindow = false

# Drawing window and Transparent breaks statusline and tabline.
## Transparent window alpha
## Note: This setting also implicitly enables the Drawborder setting
#Transparent = 0.95
##
## Drawing window border instead of vertical split, statusline
#DrawBorder = true

ExtCmdline = false
ExtPopupmenu = false
ExtTabline = false
ExtMessages = false

IndentGuide = true

DiffAddPattern    = 1
DiffDeletePattern = 1
DiffChangePattern = 1
# ClickEffect = true

# [Palette]
# ## Specifies the proportion of the command line palette to the height of the entire window.
# AreaRatio = 0.5
# ## Specifies the number of items to be displayed in the command line palette.
# MaxNumberOfResultItems = 30
# ## Specifies the opacity of the command line palette.
# Transparent = 1.0

# [Message]
# ## Specifies the opacity of the message window.
# Transparent = 1.0

[Statusline]
Visible = false

# Options: “textLabel” / “icon” / “background” / “none”
ModeIndicatorType = "textLabel"

# Optional setting colors per Neovim editing modes
NormalModeColor = "#3cabeb"
CommandModeColor = "#5285b8"
InsertModeColor = "#2abcb4"
ReplaceModeColor = "#ff8c0a"
VisualModeColor = "#9932cc"
TerminalModeColor = "#778899"

# Statusline components
Left = [ "mode", "filepath", "filename" ]
Right = [ "message", "git", "filetype", "fileformat", "fileencoding", "curpos", "lint" ]

[Palette]
Transparent = 0.8

[Message]
Transparent = 0.8

[Popupmenu]
## neovim's popupmenu is made up of word, menu and info parts.
## Each of these parts will display the following information.
##   word:   the text that will be inserted, mandatory
##   menu:   extra text for the popup menu, displayed after "word"
##   info:   more information about the item, can be displayed in a preview window

## The following options specify whether to display a dedicated column in the popupmenu
## to display the long text displayed in the `info` part.
ShowDetail = true

## total number to display item
Total = 15

## width of `menu` column
MenuWidth = 400

## width of `info` column
InfoWidth = 1

## width of `detail` column
DetailWidth = 250

[Tabline]
VIsible = true

[Lint]
Visible = false

[ScrollBar]
Visible = false

[MiniMap]
Visible = false
# # Restore session — information that was ended without being saved
# RestoreSession = false

# File open command in gonvim file explorer
