# ~/.goneovim/setting.toml

[Editor]
# Editor minimum window width (>= 800)
Width = 1400
# Editor minimum window height (>= 600)
Height = 900

# Editor external font-family, font-size, and linespace.
FontFamily = "Cica"
FontSize = 12
Linespace = 0

# Drawing window border instead of vertical split, statusline
DrawBorder = true

# Copy yanked text to clipboard
Clipboard = true

# Disable IME in Normal mode
DisableImeInNormal = false

# Transparent window alpha
# Note: This setting also implicitly enables the Drawborder setting
Transparent = 0.8

[Statusline]
Visible = true

# Options: “textLabel” / “icon” / “background” / “none”
ModeIndicatorType = "textLabel"

# Optional setting colors per Neovim editing modes
NormalModeColor = "#3cabeb"
CommandModeColor = "#5285b8"
InsertModeColor = "#2abcb4"
ReplaceModeColor = "#ff8c0a"
VisualModeColor = "#9932cc"
TerminalModeColor = "#778899"

# Statusline components
Left = [ "mode", "filepath", "filename" ]
Right = [ "message", "git", "filetype", "fileformat", "fileencoding", "curpos", "lint" ]

[Palette]
Transparent = 0.8

[Message]
Transparent = 0.8

[Popupmenu]
# show detail column
ShowDetail = true
# total number to display item
Total = 20
# width of `menu` column
MenuWidth = 400
# width of `info` column
InfoWidth = 1
# width of `detail` column
DetailWidth = 250


[Tabline]
Visible = true

# # Restore session — information that was ended without being saved
# RestoreSession = false

# File open command in gonvim file explorer
